= Programmiersprachen


== HTML & CSS 

HTML und CSS bilden die Grundlagen des Webbrowsers.
Während HTML die Strukturierung einer Webseite vorgibt, 
sorgt CSS dafür, dass sie schön aussieht.
Das Web basiert auf der Verwendung von HTML 
und ohne kann eine Webseite nicht existieren.

Somit werden HTML und CSS hauptsächlich im Web Anwendungen verwendet, 
aber durch diverse Werkzeuge kann man mithilfe
von HTML auch Anwendungen für Android, iOS und andere Betriebssysteme bauen.

Viele scheuen davor Zurück HTML als eine Programmiersprache zu bezeichnen,
weil es keinerlei verhalten besitzt 
und grundlegende Dinge, 
wei if Abfragen oder Schleifen zur Kontrolle eines Programms fehlen.
Dennoch ist HTML unerlässlich für die Entwicklung für Web Anwendungen,
weshalb es hier aufgeführt ist.

== JavaScript und TypeScript

Während HTML und CSS das Aussehen einer Webseite bestimmten,
bestimmt JavaScript das verhalten auf einer HTML Seite.

JavaScript ist eine interpretierte Sprache,
die dynamisch typisiert 
und typ unsicher ist.
Sie besitzt einen garbage collector 
und unterstützt mehrere Paradigmen.

Sie wurde im Jahr 1995 von Netscape für dynamische HTML Seiten im Webbrowser entwickelt.
Heute wird JavaScript nicht mehr nur verwendet um Webseiten dynamisch darzustellen 
sondern wird auch im Hintergrund verwendet um Funktionalitäten auf Servern möglich 
zu machen.

JavaScript ist wohl eine der Umstrittensten Sprachen die es gibt. 
Es existieren tausende von Frameworks und sie wird von vielen geliebt 
aber von mindestens genau so vielen gehasst.

Während ihre Ursprüngliche Verwendung nur Web Anwendungen waren,
wo sie auch immer noch stark verbreitet ist 
und fast die einzige Möglichkeit ist um dynamische Seiten dar zu stellen,
wird sie heute auch 
für normale Applikationen auf Android, iOS und anderen Systemen genutzt.
Sie findet auch ihre Anwendung in Machine Learning, Data science und game development.

JavaScript ist eine Sprache mit vielen Anwendungsmöglichkeiten,
die durch ihre starke Generalität und weite Verbreitung möglich wurden.

=== TypeScript

TypeScript ist ein sogenanntes Superset von JavaScript. 
Das bedeutet,
dass TypeScript JavaScript einfach erweitert.
Die wichtigen Feature, 
die TypeScript bei vielen beliebt machen sind,
zum einen die statische Typisierung der Sprache und die damit einhergehende Typsicherheit,
welche eine frühe Erkennung von bugs möglich macht
und zum anderen die Eigenschaft, 
dass TypeScript eine Sprache ist, 
die einen Transpiler verwendet.
Ein Transpiler ist eine Art von Compiler,
die den Code von einer Sprache in den Code einer anderen Sprache umwandelt.
Somit kann TypeScript zu jeder Version von JavaScript kompiliert werden.
Das ermöglicht es neue Features zu verwenden,
die dann zu älteren Versionen von JavaScript kompiliert werden,
in denen diese Features nicht existierten.

== PHP

Ist eine dynamisch typisierte, 
interpretierte Sprache, 
mit einem garbage collector und Unterstützung für viele Paradigmen.
PHP wird hauptsächlich zur Erstellung von Webseiten verwendet wird.
Im Gegensatz zu JavaScript wird die Sprache nicht direkt im 
Browser ausgeführt sondern vom Server, 
welcher dann eine veränderte Seite basierend auf dem PHP Code an 
den User schickt.

PHP wird ausschließlich in der Webentwicklung verwendet 
und betreibt Frameworks wie Wordpress 
und Internetseiten, wei Wikipedia.

== Ruby 

Ruby ist eine interpretierte, 
dynamisch Typisierte Sprache,
mit einem garbage collector.
Ruby wurde hauptsächlich für Objekt orientierte Programmierung entwickelt, 
unterstützt aber auch andere Paradigmen.

Ruby findet vor allem Verwendung in der Webentwicklung mit dem Framework Ruby on Rails,
welches bekannte Webseiten wie GitHub betreibt.
Ruby wird auch als Skriptsprache verwendet um kleinere Aufgaben auf Linux, Windows oder iOS zu erfüllen.
Vereinzelt wird Ruby auch in der Entwicklung von Spielen verwendet.


== Java

Java ist eine kompilierte,
Objekt orientierte, 
statisch typisierte Sprache mit Typsicherheit,
die einen garbage collector verwendet.

Java ist vor allem aufgrund der Java Virtual Machine (JVM) sehr beliebt,
welche eine Plattformunabhängigkeit ermöglicht.
Diese Unabhängigkeit sorgt auch dafür, 
dass sie die Grundlage für Android Apps bildet.

Heute wird Java für Web und App Entwicklung verwendet, 
sowie für data science, 
künstliche Intelligenz,
Spieleentwicklung und auch auf Eingebetteten Systemen.

Auch wenn Java bei vielen Programmierern sehr verhasst ist,
wird sie durch die JVM und ihre weite Verbreitung
wahrscheinlich auch in der Zukunft noch große Verwendung finden.
Die JVM ermöglicht auch die Verwendung von anderen Sprachen
wie Clojure, Kotlin und Scala,
welche auch in vielen Bereichen beliebt sind.


== Objective-C und Swift

Objective-C und Swift sind Programmiersprachen,
die hauptsächlich, wenn nicht sogar ausschließlich, 
von Apples Ökosystem verwendet werden.
Swift ist hierbei der Nachfolger von Objective-C,
in dem Sinne,
dass auf Apple Geräten Objective-C zusammen mit Swift im
selben Programm ausgeführt werden können.
Die beiden Sprachen sind fast unerlässlich für 
Programme auf Apple Geräten aber haben außerhalb dessen keine Existenzberechtigung.

== Dart

Dart ist eine Objekt orientierte Sprache,
die aber auch andere Paradigmen unterstützt,
mit einem garbage collector,
die sich sowohl statisch als auch dynamisch typisiert verhalten kann
durch die Verwendung von unterschiedlichen Schlüsselwörtern.
Sie wurde von Google entwickelt und war ursprünglich als Nachfolger für JavaScript gedacht.
Dart kann zu nativen Code für die Appentwicklung kompiliert werden,
aber auch zu JavaScript in Webanwendungen.

Dart wird vor allem in der Entwicklung von Cross-platform Anwendungen verwendet
mithilfe des Frameworks Flutter.
Auch wenn die Sprache mehr Fähigkeiten hat,
findet sie momentan nicht viel Verwendung für direkte App- oder Webentwicklung.


== Golang

Statisch typisierte, kompilierte Sprache mit garbage collection.
Go kann auch zu JavaScript transpiled werden.
Go wird unter anderem auch von Google, Uber und Twitch benutzt,
wobei Go sogar von Google entwickelt wurde.

Go ist vor allem für eine gute performance und einfache Lesbarkeit bekannt.

Meistens wird Go für die Entwicklung von Infrastruktur für Web Anwendungen
verwendet,
aber es findet auch Verwendung in der App Entwicklung, 
künstlichen Intelligenz
und eingebetteten Systemen,
sowie der Spiele Entwicklung.

== C, C++ und Rust

C, C++ und Rust sind alle drei Sprachen ohne garbage Collection,
die hauptsächlich für eingebettete Systeme verwendet werden.
Hierbei ist C die älteste Sprache,
die nur Prozedurale Programmierung unterstützt.
Auf der anderen Seite ist C eine der am weitesten verbreiteten Sprachen
und ist vor allem dafür bekannt, 
dass sie die Grundlage für sehr viele Sprachen wie 
C++, Java, Python, Objective-C und viele mehr Bildet,
sowie die Grundlage für fast alle bekannten Betriebssysteme.

C++ wird von ihrem Entwickler als Superset von C mit wenigen ausnahmen bezeichnet.
Ein großer unterschied zwischen C und C++ ist das unterstützen von Objekt orientierter
Programmierung.
Sie wird auch heute noch viel Verwendet für eingebettete Systeme aber auch
für App- und Web Entwicklung, 
sowie Spieleentwicklung, 
da sie die Grundlage für bekannte Engines wie die Unreal Engine bildet.

Rust ist die neuste von den drei genannten Programmiersprachen und
unterstützt mehrere Paradigmen.
Rust hat vor allem durch das sogenannte Ownership Konzept
und andere neuere Konzepte eine große Beliebtheit.
Das Ownership Konzept ermöglicht hierbei eine besondere Art
über Speicher nach zu denken,
welche das Programmieren stark vereinfacht und Bugs vorbeugt.

== C# (C Sharp)

Auch wenn C# wie eine Erweiterung von C++ wirkt, 
weil es auch nur zwei weitere plus Zeichen hinzufügt,
hat C# mehr Ähnlichkeit mit Java,
als mit C++.
C# ist eine typsicher, statisch typisierte,
kompilierte und objektorientiert Sprache mit einem garbage collector.

C# zeichnet sich vor allem dadurch aus, 
dass es von Microsoft und dem .NET Framework gestützt wird.
C# wurde anfänglich ausschließlich für Windows entwickelt 
und bildet daher die Grundlage für viele Applikationen auf Windows,
sie kann aber inzwischen auch auf macOS, iOS und Android verwendet werden
und bietet auch dort die Möglichkeit der Applikationsentwicklung.
Aber auch in der Webentwicklung findet C# Anwendung.

C# und das .NET Framework ermöglichen auch die Verwendung und inkooperation von
anderen Sprachen wie A#, F# und viele andere.

== Python

Eine Programmiersprache, 
die in einer solchen Auflistung niemals fehlen darf ist Python.
Python ist eine der beliebtesten Programmiersprachen 
durch die einfache Syntax,
garbage collection,
mehrere Paradigmen,
dynamische Typisierung
und Typsicherheit.

Python wird fast überall verwendet.
Im Machine learning Bereich, 
hat Python Java als die beliebteste Sprache abgelöst.
Auch in der Webentwicklung kann Python für fast alles verwendet werden,
selbst anstatt Javascript durch Projekte wie Brython.

Die einzige Ausnahme für den Verwendungsbereich sind eingebettete Systeme.
Da Python eine vergleichsweise langsame Sprache ist,
bietet sie sich nicht an für eingebettete Systeme,
die häufig eine schnelle Ausführungszeit benötigen.

== R und Matlab

Zu guter letzte,
kommen wir noch zu R und Matlab.
Die beiden Sprachen haben nicht viel miteinander zu tun
abgesehen davon, 
dass sie Domänen spezifische Sprachen sind.
Während R vor allem im Bereich Data Science und Statistik Anwendung findet,
wird Matlab häufig für Mathematische Probleme verwendet.

Beide Sprachen können durchaus für mehr verwendet werde als ihre Domäne,
aber dennoch würden die meisten Programmierer nicht zu diesen Sprachen
greifen um Probleme außerhalb ihrer Domäne zu lösen.

// In meinen Augen, 
// und das ist wirklich das einzige Statement, 
// dass ich nur aus meiner Sicht machen kann,
// werden solche Domänen Spezifische sprachen häufig von
// Leuten verwendet,
// die selber wenig Erfahrung mit Programmierung 
// und anderen Sprachen haben,
// da die Konzepte in diesen Sprachen häufig speziell für die Domäne gelöst werden
// und nicht in einem Generellen Ansatz, 
// wie andere Programmiersprachen.
// Dieses Statement muss mit einer Hand voll Salz genossen werden,
// da ich selber nur wenig Berührung mit diesen Sprachen hatte 
// und auch andere Programmierer, 
// die ich kenne, 
// lieber einen Bogen um diese Sprachen machen.

