= Zusammenfassung

In dieser Aufstellung haben wir
nun einige Programmiersprachen 
und die Bereiche in denen sie benutzt werden kennen gelernt.
Dieser Vortrag soll lediglich einen groben
Überblick über die Sprachen 
und ihre Anwendungsbereiche geben.

Des weiteren, 
erhebe ich keinerlei Anspruch auf Vollständigkeit.
Weder die Anwendungsbereiche noch die genannten Programmiersprachen
sind ansatzweise vollständig.
Viele Programmiersprachen, 
die vor allem in der Vergangenheit genutzt wurden,
als auch Sprachen die heute verwendet werden,
wurden hier nicht aufgelistet.
Die genannten Programmiersprachen sind Sprachen,
von denen ich 
durch meinem Studium,
durch Literatur 
und durch andere 
häufig gesehen habe.
Aber selbst die aufgelisteten Sprachen sind nicht alle
Sprachen in denen ich schon programmiert habe,
geschweige denn alle von denen ich schon gehört habe.

Jede Sprache hat ihre Vor- und Nachteile 
und ihre Verwendbarkeit oder Berechtigung.
Man sollte sich immer darüber im klaren sein,
dass jede Sprache aus einem Grund verwendet wird 
und aus einem Grund entwickelt wurde.
Neue Konzepte werden täglich erfunden 
oder anders interpretiert.
Eine neue Sprache zu lernen kann nur die eigene Erfahrung erweitern
und vielleicht sogar das eigene Denken verbessern.

Sei das gesagt, 
so ist es doch auch wichtig, 
dass man erst Mal eine Sprache lernt 
und danach nach dem die Grundkonzepte verstanden wurden
sich in neue hineinstürzt.
In meinen Augen ist Java eine gute erste Programmiersprache
mit der ich auch angefangen habe.
Dennoch sollte man nachdem man eine Sprache gut beherrscht 
auch mal einen Blick auf andere Werfen
und vielleicht hilft bei diesem Blick dann auch diese Übersicht.
