name: Build LaTeX document
on: [push]

env:
  TEX_FILE_NAME: Programmiersprachen

jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: $TEX_FILE_NAME.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: $TEX_FILE_NAME.aux
          compiler: bibtex
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: $TEX_FILE_NAME.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
